<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>426.3.2</Version>
    <Description>Core/base module</Description>    
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl></PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>extended SecurityContext behaviour with role display name</PackageReleaseNotes>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>ws3dx.core.snk</AssemblyOriginatorKeyFile>
    <RepositoryUrl>https://github.com/3ds-cpe-emed/ws3dx-dotnet</RepositoryUrl>
    <PackageLicenseFile>MITlicense.txt</PackageLicenseFile>
    <Product>3DEXPERIENCE Web Services Client SDK for Dotnet Core</Product>
    <RepositoryType>git</RepositoryType>
     <Nullable>disable</Nullable>
     <PackageTags>3DEXPERIENCE</PackageTags>
  </PropertyGroup>

   <ItemGroup>
     <ProjectReference Include="..\ws3dx.shared\ws3dx.shared.csproj" />
   </ItemGroup>

   <ItemGroup>
     <None Include="MITlicense.txt">
       <Pack>True</Pack>
       <PackagePath></PackagePath>
     </None>
   </ItemGroup>

</Project>
