<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
     <Version>427.0.0</Version>
     <Title>3DEXPERIENCE Engineering Web Services .NET Client</Title>
     <Description>3DEXPERIENCE Engineering Web Services .NET Client</Description>
     <PackageProjectUrl></PackageProjectUrl>
     <RepositoryUrl>https://github.com/3ds-cpe-emed/ws3dx-dotnet</RepositoryUrl>
     <PackageTags>3DEXPERIENCE</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ws3dx.core\ws3dx.core.csproj" />
  </ItemGroup>

 

</Project>
