<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
     <Version>426.3.2</Version>
     <Title>3DEXPERIENCE Manufacturing Item Web Services .NET Client</Title>
     <Company />
     <Description>3DEXPERIENCE Manufacturing Item Web Services .NET Client</Description>
     <RepositoryUrl>https://github.com/3ds-cpe-emed/ws3dx-dotnet</RepositoryUrl>
     <PackageTags>3DEXPERIENCE DELMIA</PackageTags>
     <PackageReleaseNotes>fix: ISpecifiedOccurrence json property names missing</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ws3dx.core\ws3dx.core.csproj" />
  </ItemGroup>

 

</Project>
